### ISSUE TITLE
generate_run.py needs to normalize scores

### ISSUE THREAD

**Issue by isoboroff** [irlabamsterdam/iKAT#5]
The generate_run.py script concatenates the provenances of the ranked responses into a single ranked list:
```
9-1_1	Q0	clueweb22-en0044-34-02396:4	1	1.7389999628067017	bm25_rm3-auto-ptkb_3-k_1000-num_psg-3
9-1_1	Q0	clueweb22-en0042-65-11467:10	2	1.5957000255584717	bm25_rm3-auto-ptkb_3-k_1000-num_psg-3
9-1_1	Q0	clueweb22-en0005-74-16313:7	3	1.590499997138977	bm25_rm3-auto-ptkb_3-k_1000-num_psg-3
9-1_1	Q0	clueweb22-en0040-73-15722:6	4	1.9833999872207642	bm25_rm3-auto-ptkb_3-k_1000-num_psg-3
9-1_1	Q0	clueweb22-en0040-73-15722:5	5	1.9539999961853027	bm25_rm3-auto-ptkb_3-k_1000-num_psg-3
9-1_1	Q0	clueweb22-en0040-73-15722:4	6	1.7603000402450562	bm25_rm3-auto-ptkb_3-k_1000-num_psg-3
```
Note the first three passages are from the first ranked response, and the second three are from the next response.  (These are using the baseline automatic run.)

The problem is that trec_eval sorts runs by score, and ignores the rank field, for historical reasons.  So documents in ranks 4, 5, and 6 will be sorted ahead of 1,2,3 for scoring using trec_eval.

This would make sense if you wanted to assume all provenance scores within a turn were comparable.  In CAsT, we didn't assume that, and scores were normalized using the inverse rank:

`provenance.score = (1 / (response.rank+1)) * provenance.score`

**Comment by aliannejadi** [comment]
Thank you, Ian for checking this. We'd like to do the same for iKAT. @andrewramsay could you please make the required change in the code?

**Comment by andrewramsay** [comment]
I'd added this script from the main branch of Paul's CAsT repo but it looks like there was a newer version in a different branch that includes the normalized scoring, should have used that instead! Will update this copy in the morning.
